### ISSUE TITLE
changes to go.mod enables "default" installation

### ISSUE THREAD

**Issue by patrickhener** [TheZoraiz/ascii-image-converter#1]
I read your reddit post and tried to install your tool using the "default" go way of doing this:

```bash
go get -u go get -u github.com/TheZoraiz/ascii-image-converter
go install github.com/TheZoraiz/ascii-image-converter@latest
```

This would esentially work if the first line of your `go.mod` file was like this:
```bash
module github.com/TheZoraiz/ascii-image-converter
```

Best regards

**Comment by TheZoraiz** [comment]
Thanks for pointing that out! I'll make said changes.
