### ISSUE TITLE
Cannot open image in standard command prompt on Windows 10 21H1

### ISSUE THREAD

**Issue by PIndividual** [TheZoraiz/ascii-image-converter#10]
when dragging and drop the image path on windows, it always gives out an error message, but when running cmd in admin mode, drag and drop simply won't work.

**Comment by PIndividual** [comment]
![image](https://user-images.githubusercontent.com/62368342/132778087-06e68a7e-1511-4b79-bac6-cd62b9af2409.png)

**Comment by TheZoraiz** [comment]
`ascii-image-converter` supports image urls, so I think the url validating library is confusing the "c:\\" in the file path as a url. Will look into this and patch soon. Thanks for reporting!

**Comment by TheZoraiz** [comment]
Patched this issue in v1.9.2. Only inputs with `http://` and `https://` initials should now be considered as urls. I just tested and drag and drop works on windows now. Let me know if it works on your end.

**Comment by PIndividual** [comment]
Looks good for me now, BTW why coloring in cmd is not working, if it is the issue caused by cmd itself, are there other command prompt software that support image coloring in Windows? Thanks XD.

**Comment by PIndividual** [comment]
![image](https://user-images.githubusercontent.com/62368342/132949810-62b5d7d7-6b01-43cb-beae-0b5f6e5438ce.png)

**Comment by TheZoraiz** [comment]
You seem to be using the `-c` flag. The coloring flag is `-C` with a capital C. Lowercase `-c` just adds more characters in ascii art. Execute `ascii-image-converter -h` for more details.

Anyways, I'm closing this issue since it appears to be solved.
