### ISSUE TITLE
Clear ansi-colored output

### ISSUE THREAD

**Issue by nadevko** [TheZoraiz/ascii-image-converter#25]
1. When characters in the row have the same color, will be better print escape code only once: `\e[38;5;20mw\e[38;5;20mm` -> `\e[38;5;20mwm`
2. Use only space as invisible character, when background and text have same color: `\e[38;5;0m<char>` -> `\e[38;5;0m `

Also, will be cool mixing `--color` and `--color-bg`. Maybe, in form `--color=(fg|bg|both)`

**Comment by TheZoraiz** [comment]
Looks like too much work for too little gain. There aren't any significant performance improvements, and it would just make the code a readability nightmare (more than it already is...). I also can't accept the flag alteration request as too many projects depending on ascii-image-converter will break.
