### ISSUE TITLE
ascii image converter saving formats

### ISSUE THREAD

**Issue by Genialngash** [TheZoraiz/ascii-image-converter#3]
i have a suggestion if there's a way for program can save the a colored ascii image. Such an improvement will be very great.

**Comment by TheZoraiz** [comment]
@Genialngash Thanks for the suggestion! Actually I thought of that before but chose to not implement it. The colors you see with the --color flag in the terminal are actually escape codes which the terminal converts into colored text. See [this gist](https://gist.github.com/XVilka/8346728) for more info.

If one were to save this output in a .txt file, it'd look something like this:
<p align="center">
  <img width="600" src="https://user-images.githubusercontent.com/53083869/120349710-c4e5f100-c317-11eb-9736-4442561d82ee.png">
</p>

Now, you can copy and paste this from the terminal with a command like `cat` and retain the results, but that's probably not the usecase most people are looking for when they want to save ascii art.

I'll think about this and leave this issue open in case someone else can come up with a workaround.

**Comment by TheZoraiz** [comment]
@Genialngash The recently released version 1.3.0 now supports exporting ascii art as PNG images now. I believe that should cover the lack of an option for saving colored output. Will close this issue in a day.
