### ISSUE TITLE
The saved ascii art in txt, is not working properly

### ISSUE THREAD

**Issue by Lufims** [TheZoraiz/ascii-image-converter#30]
When I use the command to save the ascii art in a txt file, it not displays properly, I think it's because the spaces or line breaks that the script don't do.
![Screenshot_5](https://user-images.githubusercontent.com/73536178/200196498-7428e700-ef94-4e8a-8b9c-82ff511907d8.png)

**Comment by TheZoraiz** [comment]
I remember encountering this problem in one of my old PCs, and I think it's an issue with the text editor not interpreting new lines characters correctly. Could you try reading the saved txt file from a different text editor?

**Comment by Lufims** [comment]
> I remember encountering this problem in one of my old PCs, and I think it's an issue with the text editor not interpreting new lines characters correctly. Could you try reading the saved txt file from a different text editor?

It worked now
![Screenshot_6](https://user-images.githubusercontent.com/73536178/200347115-3f74b232-c9d3-4b60-aaac-07da2bcf8228.png)

**Comment by TheZoraiz** [comment]
Neat, guess that solves the issue :)
