### ISSUE TITLE
Save animated gif

### ISSUE THREAD

**Issue by bitnom** [TheZoraiz/ascii-image-converter#33]
How to save frames of animated gif for html/js output?

**Comment by TheZoraiz** [comment]
The only saving functionality available for ascii art gifs is in the form of gifs with `--save-gif` flag. You will have to split the gif into its frames manually before feeding them to `ascii-image-converter` if you want to have each frame converted separately.

Doesn't look like an issue with the project, so I'm closing this. Please discuss such matters in the [`Discussions`](https://github.com/TheZoraiz/ascii-image-converter/discussions) tab.
