### ISSUE TITLE
Working in Bash but not in Zsh

### ISSUE THREAD

**Issue by iamBijoyKar** [TheZoraiz/ascii-image-converter#45]
I am using wsl in Windows 11.  I am getting 

`zsh: command not found: ascii-image-converter`

But in bash it is working fine.

Can anyone please help me to fix this issue? I am new in this.

**Comment by TheZoraiz** [comment]
Your zsh config's `PATH` environment variable probably doesn't have path for `ascii-image-converter`'s directory. Find that path from bash by running `which ascii-image-converter` and add it to zsh's `PATH`

**Comment by iamBijoyKar** [comment]
I was having problem to setup the path for zsh, so reinstall using `apt` using this guide 👇 

![image](https://github.com/TheZoraiz/ascii-image-converter/assets/85790967/6fececdd-d243-467e-8b8b-77c7c0df4082)

Now it is working. Great product!!

Thank you very much for the fast response. I really appreciate this 👍
