### ISSUE TITLE
My results are not as good as your examples. 

### ISSUE THREAD

**Issue by deroverda** [TheZoraiz/ascii-image-converter#46]
Hi. Looking at the example pictures it looks bloody great. 

But when I tested [this image, 1510x1077](https://imgur.com/a/41Pmg82) 

it turned out like [this](https://imgur.com/LtS6ZQF)

am I doing something wrong? should the dimensions be something else for better results? confused as hell. 

thanks in advance. 

PS. using [Cmder](https://cmder.app/) as my cmd. Don't know if that has something to do with it.

**Comment by TheZoraiz** [comment]
Ascii art can be a hit or miss depending on the image. Fortunately you can tune the results by:

- Creating a larger output with bigger dimensions. More space means more details not lost through resizing.
- Using a different character set. If the default character set isn't giving you the desirable result, you can change it with `-m` flag.

You could also try braille art, which is working well with your image. And please use the Discussions tab to discuss non-issues in the future.
