### ISSUE TITLE
Error: your terminal supports neither 24-bit nor 8-bit colors.

### ISSUE THREAD

**Issue by SoCkEt7** [TheZoraiz/ascii-image-converter#48]
im running a command with shell_exec from ascii-image-converter

<?php
$cmd = "ascii-image-converter $fichier -s ./assets/images/ascii $width $negative $color --only-save -c";
$output=shell_exec($cmd);
?>
Error: your terminal supports neither 24-bit nor 8-bit colors. Other coloring options aren't available
But when i run this specific command on my bash it work

This is my own server so i can configure it as i want.

Any ideas ?

**Comment by TheZoraiz** [comment]
`shell_exec` is running in a headless environment and doesn't have access to an interactive terminal, which is needed to check terminal supported colors. Your best bet would be to pre-generate ascii art through bash, and use the exported text instead.

Besides, it's all escape codes around characters which the terminal converts to colors, but you'll just get the raw text if you serve as a website through a server.
