### ISSUE TITLE
Wrong -C output

### ISSUE THREAD

**Issue by sicxu** [TheZoraiz/ascii-image-converter#9]
When I use the "-C" to display the output, the result is wired. The image saved using "--save-img" seems to be fine.

the output displayed in the terminal.
![image](https://user-images.githubusercontent.com/64250193/132691725-e149a1f4-c94c-4743-973e-f4c3e02ecd67.png)

the saved result
![leo-ascii-art](https://user-images.githubusercontent.com/64250193/132692179-3d922897-2336-4ab2-b94d-3504e4d0ca75.png)

**Comment by TheZoraiz** [comment]
It seems your terminal doesn't support True color escape codes. Try using a different terminal emulator like `xterm` (or `iTerm2` for macOS) and see if the results differ.

**Comment by sicxu** [comment]
I tried iTerm2, and it works now. Thanks for your reply.

**Comment by TheZoraiz** [comment]
@sicxu Just released v1.10.0 that supports 8-bit colors. You should be able to see colored ascii art in your usual terminal now :)
